name: CrunchPHP.de
description: Blog about code snippets and programming things. Mostly about PHP. Or related.
url: http://www.crunchphp.de
markdown: redcarpet
pygments: true
timezone: Europe/Berlin
encoding: UTF-8
debug: true
assets:
    js_compressor: uglifier
    css_compressor: sass
permalink: /:year:month/:title.html
